logging.level.ROOT: WARN

spring:
    cloud:
        stream:
            bindings:
                couponUsing:
                    destination: testtopic
                couponUsed:
                    destination: testtopic
                    consumer:
                      autoCommitOffset: false
                      autoCommitOnError: false